export const cityChoices = [
  { value: '01', label: 'Adana', country: 'TR' },
  { value: '02', label: 'Adıyaman', country: 'TR' },
  { value: '03', label: 'Afyonkarahisar', country: 'TR' },
  { value: '04', label: 'Ağrı', country: 'TR' },
  { value: '05', label: 'Amasya', country: 'TR' },
  { value: '06', label: 'Ankara', country: 'TR' },
  { value: '07', label: 'Antalya', country: 'TR' },
  { value: '08', label: 'Artvin', country: 'TR' },
  { value: '09', label: 'Aydın', country: 'TR' },
  { value: '10', label: 'Balıkesir', country: 'TR' },
  { value: '11', label: 'Bilecik', country: 'TR' },
  { value: '12', label: 'Bingöl', country: 'TR' },
  { value: '13', label: 'Bitlis', country: 'TR' },
  { value: '14', label: 'Bolu', country: 'TR' },
  { value: '15', label: 'Burdur', country: 'TR' },
  { value: '16', label: 'Bursa', country: 'TR' },
  { value: '17', label: 'Çanakkale', country: 'TR' },
  { value: '18', label: 'Çankırı', country: 'TR' },
  { value: '19', label: 'Çorum', country: 'TR' },
  { value: '20', label: 'Denizli', country: 'TR' },
  { value: '21', label: 'Diyarbakır', country: 'TR' },
  { value: '22', label: 'Edirne', country: 'TR' },
  { value: '23', label: 'Elazığ', country: 'TR' },
  { value: '24', label: 'Erzincan', country: 'TR' },
  { value: '25', label: 'Erzurum', country: 'TR' },
  { value: '26', label: 'Eskişehir', country: 'TR' },
  { value: '27', label: 'Gaziantep', country: 'TR' },
  { value: '28', label: 'Giresun', country: 'TR' },
  { value: '29', label: 'Gümüşhane', country: 'TR' },
  { value: '30', label: 'Hakkâri', country: 'TR' },
  { value: '31', label: 'Hatay', country: 'TR' },
  { value: '32', label: 'Isparta', country: 'TR' },
  { value: '33', label: 'Mersin', country: 'TR' },
  { value: '34', label: 'İstanbul', country: 'TR' },
  { value: '35', label: 'İzmir', country: 'TR' },
  { value: '36', label: 'Kars', country: 'TR' },
  { value: '37', label: 'Kastamonu', country: 'TR' },
  { value: '38', label: 'Kayseri', country: 'TR' },
  { value: '39', label: 'Kırklareli', country: 'TR' },
  { value: '40', label: 'Kırşehir', country: 'TR' },
  { value: '41', label: 'Kocaeli', country: 'TR' },
  { value: '42', label: 'Konya', country: 'TR' },
  { value: '43', label: 'Kütahya', country: 'TR' },
  { value: '44', label: 'Malatya', country: 'TR' },
  { value: '45', label: 'Manisa', country: 'TR' },
  { value: '46', label: 'Kahramanmaraş', country: 'TR' },
  { value: '47', label: 'Mardin', country: 'TR' },
  { value: '48', label: 'Muğla', country: 'TR' },
  { value: '49', label: 'Muş', country: 'TR' },
  { value: '50', label: 'Nevşehir', country: 'TR' },
  { value: '51', label: 'Niğde', country: 'TR' },
  { value: '52', label: 'Ordu', country: 'TR' },
  { value: '53', label: 'Rize', country: 'TR' },
  { value: '54', label: 'Sakarya', country: 'TR' },
  { value: '55', label: 'Samsun', country: 'TR' },
  { value: '56', label: 'Siirt', country: 'TR' },
  { value: '57', label: 'Sinop', country: 'TR' },
  { value: '58', label: 'Sivas', country: 'TR' },
  { value: '59', label: 'Tekirdağ', country: 'TR' },
  { value: '60', label: 'Tokat', country: 'TR' },
  { value: '61', label: 'Trabzon', country: 'TR' },
  { value: '62', label: 'Tunceli', country: 'TR' },
  { value: '63', label: 'Şanlıurfa', country: 'TR' },
  { value: '64', label: 'Uşak', country: 'TR' },
  { value: '65', label: 'Van', country: 'TR' },
  { value: '66', label: 'Yozgat', country: 'TR' },
  { value: '67', label: 'Zonguldak', country: 'TR' },
  { value: '68', label: 'Aksaray', country: 'TR' },
  { value: '69', label: 'Bayburt', country: 'TR' },
  { value: '70', label: 'Karaman', country: 'TR' },
  { value: '71', label: 'Kırıkkale', country: 'TR' },
  { value: '72', label: 'Batman', country: 'TR' },
  { value: '73', label: 'Şırnak', country: 'TR' },
  { value: '74', label: 'Bartın', country: 'TR' },
  { value: '75', label: 'Ardahan', country: 'TR' },
  { value: '76', label: 'Iğdır', country: 'TR' },
  { value: '77', label: 'Yalova', country: 'TR' },
  { value: '78', label: 'Karabük', country: 'TR' },
  { value: '79', label: 'Kilis', country: 'TR' },
  { value: '80', label: 'Osmaniye', country: 'TR' },
  { value: '81', label: 'Düzce', country: 'TR' },
  { value: 'AL', label: 'Albania' },
  { value: 'AD', label: 'Andorra' },
  { value: 'AM', label: 'Armenia' },
  { value: 'AT', label: 'Austria' },
  { value: 'AZ', label: 'Azerbaijan' },
  { value: 'BY', label: 'Belarus' },
  { value: 'BE', label: 'Belgium' },
  { value: 'BA', label: 'Bosnia and Herzegovina' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'HR', label: 'Croatia' },
  { value: 'CY', label: 'Cyprus' },
  { value: 'CZ', label: 'Czech Republic' },
  { value: 'DK', label: 'Denmark' },
  { value: 'EE', label: 'Estonia' },
  { value: 'FI', label: 'Finland' },
  { value: 'FR', label: 'France' },
  { value: 'GE', label: 'Georgia' },
  { value: 'DE', label: 'Germany' },
  { value: 'GR', label: 'Greece' },
  { value: 'HU', label: 'Hungary' },
  { value: 'IS', label: 'Iceland' },
  { value: 'IE', label: 'Ireland' },
  { value: 'IT', label: 'Italy' },
  { value: 'XK', label: 'Kosovo' },
  { value: 'LV', label: 'Latvia' },
  { value: 'LI', label: 'Liechtenstein' },
  { value: 'LT', label: 'Lithuania' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'MT', label: 'Malta' },
  { value: 'MD', label: 'Moldova' },
  { value: 'MC', label: 'Monaco' },
  { value: 'ME', label: 'Montenegro' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'MK', label: 'North Macedonia' },
  { value: 'NO', label: 'Norway' },
  { value: 'PL', label: 'Poland' },
  { value: 'PT', label: 'Portugal' },
  { value: 'RO', label: 'Romania' },
  { value: 'RU', label: 'Russia' },
  { value: 'SM', label: 'San Marino' },
  { value: 'RS', label: 'Serbia' },
  { value: 'SK', label: 'Slovakia' },
  { value: 'SI', label: 'Slovenia' },
  { value: 'ES', label: 'Spain' },
  { value: 'SE', label: 'Sweden' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'TR', label: 'Turkey' },
  { value: 'UA', label: 'Ukraine' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'VA', label: 'Vatican City' }
];


export const countries = [
  { value: 'AL', label: 'Albania' },
  { value: 'AD', label: 'Andorra' },
  { value: 'AM', label: 'Armenia' },
  { value: 'AT', label: 'Austria' },
  { value: 'AZ', label: 'Azerbaijan' },
  { value: 'BY', label: 'Belarus' },
  { value: 'BE', label: 'Belgium' },
  { value: 'BA', label: 'Bosnia and Herzegovina' },
  { value: 'BG', label: 'Bulgaria' },
  { value: 'HR', label: 'Croatia' },
  { value: 'CY', label: 'Cyprus' },
  { value: 'CZ', label: 'Czech Republic' },
  { value: 'DK', label: 'Denmark' },
  { value: 'EE', label: 'Estonia' },
  { value: 'FI', label: 'Finland' },
  { value: 'FR', label: 'France' },
  { value: 'GE', label: 'Georgia' },
  { value: 'DE', label: 'Germany' },
  { value: 'GR', label: 'Greece' },
  { value: 'HU', label: 'Hungary' },
  { value: 'IS', label: 'Iceland' },
  { value: 'IE', label: 'Ireland' },
  { value: 'IT', label: 'Italy' },
  { value: 'XK', label: 'Kosovo' },
  { value: 'LV', label: 'Latvia' },
  { value: 'LI', label: 'Liechtenstein' },
  { value: 'LT', label: 'Lithuania' },
  { value: 'LU', label: 'Luxembourg' },
  { value: 'MT', label: 'Malta' },
  { value: 'MD', label: 'Moldova' },
  { value: 'MC', label: 'Monaco' },
  { value: 'ME', label: 'Montenegro' },
  { value: 'NL', label: 'Netherlands' },
  { value: 'MK', label: 'North Macedonia' },
  { value: 'NO', label: 'Norway' },
  { value: 'PL', label: 'Poland' },
  { value: 'PT', label: 'Portugal' },
  { value: 'RO', label: 'Romania' },
  { value: 'RU', label: 'Russia' },
  { value: 'SM', label: 'San Marino' },
  { value: 'RS', label: 'Serbia' },
  { value: 'SK', label: 'Slovakia' },
  { value: 'SI', label: 'Slovenia' },
  { value: 'ES', label: 'Spain' },
  { value: 'SE', label: 'Sweden' },
  { value: 'CH', label: 'Switzerland' },
  { value: 'TR', label: 'Turkey' },
  { value: 'UA', label: 'Ukraine' },
  { value: 'GB', label: 'United Kingdom' },
  { value: 'VA', label: 'Vatican City' }
];

export const nonArabAsianCountries = [
  { value: 'AF', label: 'Afghanistan' },
  { value: 'AM', label: 'Armenia' },
  { value: 'AZ', label: 'Azerbaijan' },
  { value: 'BH', label: 'Bahrain' },
  { value: 'BD', label: 'Bangladesh' },
  { value: 'BT', label: 'Bhutan' },
  { value: 'BN', label: 'Brunei' },
  { value: 'KH', label: 'Cambodia' },
  { value: 'CN', label: 'China' },
  { value: 'GE', label: 'Georgia' },
  { value: 'IN', label: 'India' },
  { value: 'ID', label: 'Indonesia' },
  { value: 'IR', label: 'Iran' },
  { value: 'JP', label: 'Japan' },
  { value: 'KZ', label: 'Kazakhstan' },
  { value: 'KG', label: 'Kyrgyzstan' },
  { value: 'LA', label: 'Laos' },
  { value: 'MY', label: 'Malaysia' },
  { value: 'MV', label: 'Maldives' },
  { value: 'MN', label: 'Mongolia' },
  { value: 'MM', label: 'Myanmar' },
  { value: 'NP', label: 'Nepal' },
  { value: 'KP', label: 'North Korea' },
  { value: 'PK', label: 'Pakistan' },
  { value: 'PH', label: 'Philippines' },
  { value: 'RU', label: 'Russia' },
  { value: 'SG', label: 'Singapore' },
  { value: 'LK', label: 'Sri Lanka' },
  { value: 'SY', label: 'Syria' },
  { value: 'TJ', label: 'Tajikistan' },
  { value: 'TH', label: 'Thailand' },
  { value: 'TL', label: 'Timor-Leste' },
  { value: 'TM', label: 'Turkmenistan' },
  { value: 'UZ', label: 'Uzbekistan' },
  { value: 'VN', label: 'Vietnam' }
];
